version: '3'
services:
   app: 
        build: .
        volumes: 
            - .:/app
        ports: 
            - 3001:3000
        environment:
            HOST: localhost:3001
            RAILS_ENV: production
            RAILS_LOG_TO_STDOUT: true
            RAILS_SERVE_STATIC_FILES: true

